name: run Project1.py

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          
      - name: execyte py script
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: Project1.py
        
      - name: commit files
        run:
          git config --local user.email "action@github.com"
          git config --local user.name "Git Hub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "update logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
